name: front_balancelife
description: "A new Flutter project."

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.0.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0 
  http: ^0.13.3
  get: ^4.7.2
  provider: ^6.1.2
  flutter_svg: ^2.0.9
  fl_chart: ^0.70.2
  flutter_staggered_grid_view: ^0.7.0
  timezone: ^0.9.4
  shared_preferences: ^2.5.3
  video_player: ^2.9.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/canasta/
    - assets/cartas/
