// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoZVha3RwD9XXYUa86idyUZG6AtnmTy5Q',
    appId: '1:630829549605:web:7d5301968c81c49d4557cc',
    messagingSenderId: '630829549605',
    projectId: 'balance-life-8d64b',
    authDomain: 'balance-life-8d64b.firebaseapp.com',
    storageBucket: 'balance-life-8d64b.firebasestorage.app',
    measurementId: 'G-RMKNPCSG0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZc828HNKWYq8ILBQFKb1jYUfDRgCE-s',
    appId: '1:630829549605:android:38845b19551317f34557cc',
    messagingSenderId: '630829549605',
    projectId: 'balance-life-8d64b',
    storageBucket: 'balance-life-8d64b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATt-lCSTm1sGnPkejPikQnnsXmGqMm7HE',
    appId: '1:630829549605:ios:d064614408a8d8f34557cc',
    messagingSenderId: '630829549605',
    projectId: 'balance-life-8d64b',
    storageBucket: 'balance-life-8d64b.firebasestorage.app',
    iosBundleId: 'com.example.frontBalancelife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATt-lCSTm1sGnPkejPikQnnsXmGqMm7HE',
    appId: '1:630829549605:ios:d064614408a8d8f34557cc',
    messagingSenderId: '630829549605',
    projectId: 'balance-life-8d64b',
    storageBucket: 'balance-life-8d64b.firebasestorage.app',
    iosBundleId: 'com.example.frontBalancelife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoZVha3RwD9XXYUa86idyUZG6AtnmTy5Q',
    appId: '1:630829549605:web:714d60856439c8034557cc',
    messagingSenderId: '630829549605',
    projectId: 'balance-life-8d64b',
    authDomain: 'balance-life-8d64b.firebaseapp.com',
    storageBucket: 'balance-life-8d64b.firebasestorage.app',
    measurementId: 'G-38Q3XYELQQ',
  );
}
